name: Publish to PyPI
on:
  release:
    types: [published]
  workflow_dispatch:

permissions:
  contents: read
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: deploy
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
            user: __token__
            password: ${{ secrets.PYPI_API_TOKEN }}
            verbose: true
            print_hash: true